static struct ggml_type_traits type_traits[] = {
    [GGML_TYPE_Q3_K_HIFI] = {
        .type_name      = "Q3_K_HIFI",
        .blck_size      = Q3_K_HIFI_BLOCK_SIZE,
        .type_size      = sizeof(block_q3_k_hifi),
        .is_quantized   = true,
        .to_float       = (ggml_to_float_t) dequantize_row_q3_k_hifi,
        .from_float_ref = (ggml_from_float_t) quantize_row_q3_k_hifi_ref,
    },
    [GGML_TYPE_Q6_K_HIFI] = {
        .type_name      = "Q6_K_HIFI",
        .blck_size      = QK_K,
        .type_size      = sizeof(block_q6_k_hifi),
        .is_quantized   = true,
        .to_float       = (ggml_to_float_t) dequantize_row_q6_k_hifi,
        .from_float_ref = (ggml_from_float_t) quantize_row_q6_k_hifi_ref,
    },
    [GGML_TYPE_Q6_K_HIFI_DYNAMIC] = {
        .type_name      = "Q6_K_HIFI_DYN",
        .blck_size      = QK_K,
        .type_size      = sizeof(block_q6_k_hifi_dynamic),
        .is_quantized   = true,
        .to_float       = (ggml_to_float_t) dequantize_row_q6_k_hifi_dynamic,
        .from_float_ref = (ggml_from_float_t) quantize_row_q6_k_hifi_dynamic_ref,
    },
    [GGML_TYPE_Q6_K_HIFI_RES8] = {
        .type_name      = "Q6_K_HIFI_RES8",
        .blck_size      = QK_K,
        .type_size      = sizeof(block_q6_k_hifi_res8),
        .is_quantized   = true,
        .to_float       = (ggml_to_float_t) dequantize_row_q6_k_hifi_res8,
        .from_float_ref = (ggml_from_float_t) quantize_row_q6_k_hifi_res8_ref,
    },
    [GGML_TYPE_Q5_K_HIFI_RES8] = {
        .type_name      = "Q5_K_HIFI_RES8",
        .blck_size      = QK_K,
        .type_size      = sizeof(block_q5_k_hifi_res8),
        .is_quantized   = true,
        .to_float       = (ggml_to_float_t) dequantize_row_q5_k_hifi_res8,
        .from_float_ref = (ggml_from_float_t) quantize_row_q5_k_hifi_res8_ref,
    },
    [GGML_TYPE_Q3_K_HIFI_RES8] = {
        .type_name      = "Q3_K_HIFI_RES8",
        .blck_size      = Q3_K_HIFI_BLOCK_SIZE,
        .type_size      = sizeof(block_q3_k_hifi_res8),
        .is_quantized   = true,
        .to_float       = (ggml_to_float_t) dequantize_row_q3_k_hifi_res8,
        .from_float_ref = (ggml_from_float_t) quantize_row_q3_k_hifi_res8_ref,
    },
    [GGML_TYPE_Q4_K_HIFI] = {
        .type_name      = "Q4_K_HIFI",
        .blck_size      = Q4_K_HIFI_BLOCK_SIZE,
        .type_size      = sizeof(block_q4_k_hifi),
        .is_quantized   = true,
        .to_float       = (ggml_to_float_t) dequantize_row_q4_k_hifi,
        .from_float_ref = (ggml_from_float_t) quantize_row_q4_k_hifi_ref,
    },
    [GGML_TYPE_Q2_K_HIFI] = {
        .type_name      = "Q2_K_HIFI",
        .blck_size      = Q2_K_HIFI_BLOCK_SIZE,
        .type_size      = sizeof(block_q2_k_hifi),
        .is_quantized   = true,
        .to_float       = (ggml_to_float_t) dequantize_row_q2_k_hifi,
        .from_float_ref = (ggml_from_float_t) quantize_row_q2_k_hifi_ref,
    },
};
